### PR TITLE
assert added

### PR DESCRIPTION
**Pull request by Cat-The-Developer**
merging assert branch into main branch

### CODE REVIEW

**Comment by Cat-The-Developer** [comment]
Mergin it

**Review by Aditya-Chourasia — DISMISSED** [review]

**Review by Aditya-Chourasia — APPROVED** [review]
nice work

**Review by Aditya-Web-Dev — APPROVED** [review]
looks good

**Review by Cat-The-Developer — COMMENTED** [review]
nice

**Pull request merged**
